### ISSUE TITLE
Issue with latest update?

### ISSUE THREAD

**Issue by Yoochem** [allista/AT_Utils#3] opened 2017-06-06 08:49 UTC
Hi Atilla!

I recently updated AT_Utils and some other mods through CKAN, and my game did not load afterwards. After some trial and error, I traced back the error to AT_Utils. For some reason it crashes KSP on startup. I can't say I'm very technical myself, but I thought you should know.

My mod list:

KSP: 1.2.2 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit
000_AT_Utils - 1.4.2  _(<--- manually reverted back after crash)_
Advanced Jet Engine - 2.8
B9 Part Switch - 1.7.1
B9 Aerospace Procedural Parts - 0.40.11
BD Animation Modules - 0.6.4.4
Camera Focus Changer - 1.0.1
Chatterer - 0.9.93.1804
Community Category Kit - 1.2.2
Community Resource Pack - 0.6.6
CommunityTechTree - 3.0.3
ConfigurableContainers - 2.4.0.5
Connected Living Space - 1.2.4.2
Contract Configurator - 1.22.2
Contract Pack: Historical Progression - 1.6
Contract Pack: Kerbal Academy - 1.1.7
Contract Pack: Bases and Stations - 3.6.1
Contract Pack: Grand Tour Contracts - 0.1.10.3
Contract Pack: Tourism Plus - 1.5.2
DangIt - 0.7.12
Deadly Reentry - 7.6.0.1
DistantObjectEnhancement - 1.8.1
Ferram Aerospace Research - 0.15.8.1
Firespitter - 7.5.1
Hangar - 3.3.1.1
HullcamVDSContinued - 0.1.6
Interstellar Fuel Switch - 2.5.1
JanitorsCloset - 0.2.20
Kerbal Attachment System - 0.6.2
Kerbal Engineer Redux - 1.1.2.8
KerbalHealth - 0.5.1
Kerbal Joint Reinforcement - 3.3.2
Kerbal Inventory System - 1.4.4
KSP-AVC Plugin - 1.1.6.2
KWRocketryRedux - 3.1.4
MagiCore - 1.2.5
ModularFlightIntegrator - 1.2.4
Docking Port Alignment Indicator - 6.5.2
NearFutureConstruction - 0.7.6
NearFutureElectrical - 0.8.7
NearFuturePropulsion - 0.8.7
NearFutureSolar - 0.7.2
NearFutureSpacecraft - 0.6.3
NRAP - 1.5.5.1
Procedural Parts - 1.2.10
RCS Build Aid - 0.9.1
RealBattery - 0.1.1.5
RealChute - 1.4.3
RealismOverhaul - 11.5
Real Scale Boosters - 0.15
RealSolarSystem - 12.0
Recovery Controller - 0.0.1
RemoteTech - 1.8.6
DeepFreeze Continued... - 0.23.4
RSSDateTime - 1.1
Saturatable RW - 1.12
SCANsat - 1.1.6.11
SETI-Greenhouse - 1.2.2
SolverEngines - 3.1
StationPartsExpansion - 0.4.3
StationScienceContinued - 2.2.1
Surface Mounted Stock-Alike Lights for Self-Illumination - 1.3.1
TAC Life Support - 0.13
Kerbal Alarm Clock - 3.8.4
TweakScale - 2.3.4
Universal Storage - 1.3.0.1
VenStockRevamp - 1.9.5
KSP Interstellar Extended - 1.13.10

Also see attached error log.

Let me know if you need any other info!

Cheers,

[output_log.txt](https://github.com/allista/AT_Utils/files/1054307/output_log.txt)
[error.txt](https://github.com/allista/AT_Utils/files/1054312/error.txt)

**Comment by allista** [comment] 2017-06-06 08:55
Thanks for the report. I'll see the logs and report back.

**Comment by allista** [comment] 2017-06-06 09:15
Ok. The crash occurs while PartLoader tries to compile Hangar2 part from the Hangar mod.
I haven't found any irregularities with respect to mod versions, **except** that you have TWO ModuleManager.dll which may or may not be related, but is always a bad thing. Remove one of them and ensure that you're using the latest, KSP-1.3 compatible MM. 

If that won't help, I'll explore this in more detail. But so far, as you can expect, I was unable to reproduce the crash on my end (though I have Ubuntu x64).

**Comment by metalwanderer** [comment] 2017-06-07 13:46
Hi Allista,
I'd like to confirm this report on Linux (Debian 8).  Noticed the issue a few days ago, but took me awhile to isolate it on my usual modded install (>80 mods), but I can now reproduce on a minimally modded install.  The source seems to be AT-Utils, but only occurs when Hangar is installed (presumably because AT-Utils doesn't get called otherwise).

KSP Version: 1.2.2.1622 (Linux x86_64)
Installed Modules:
- AT-Utils v1.4.3
- CommunityResourcePack 0.6.6.0
- ConfigurableContainers-Core 2.4.0.5
^ Hangar 3.3.1
- ModuleManager 2.7.6

Environment:
Reasonably up to date Debian 8 (Linux 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1), Core i7, GeForce 650M + Intel HD / Optimus.  I created a clean stock install copy (cp -la from stock install) and added it as a separate profile in CKAN.  Everything is installed through CKAN (although I forced Hangar to v3.3.1 because latest doesn't seem to be compatible with 1.2.2).

Player.log attached.  I noticed an error from primus (although KSP seems to run fine normally), so I also attempted a launch without primus.
[Player_noprimus.txt](https://github.com/allista/AT_Utils/files/1058000/Player_noprimus.txt)
[Player_primusrun.txt](https://github.com/allista/AT_Utils/files/1057996/Player_primusrun.txt)
[Player_mm28.txt](https://github.com/allista/AT_Utils/files/1058124/Player_mm28.txt)

I noticed you seem to be on 1.3, and told the previous poster to use the latest 1.3-compatible MM.  I suspect this is the source of the issue, and also why you can't reproduce (I tried using MM-2.8 with KSP-1.2.2 just for fun... no joy, log attached).  In that vein: I realize that you as a developer probably don't want to support more KSP versions than you have to, but there are a number of people who won't be using the latest version of KSP for the foreseeable future.  I won't fly without FAR, and Realism Overhaul is also pretty popular.  CKAN reports AT-Utils v1.4.3 as being 1.2.2-compatible (but not 1.3, interestingly), and Hangar 3.3.1.1 reports backwards compatibility with 1.2.2 (which doesn't seem to be the case).
I think the correct solution here is to be clear about version compatibility, both on the forums and especially the files that CKAN parses.  I'm no expert on CKAN's versioning, but I noticed that Editor Extensions Redux recently had a similar problem (latest version is 1.3-compatible but not 1.2.2).  When the new version first appeared, CKAN was auto-updating it, but now CKAN correctly shows only the previous version of EE to be compatible with 1.2.2.  ModuleManager is another one that comes to mind which shows correct version compatibility.

Thanks for your contribution! :-)  Let me know if there's any more information I can supply.

For completeness, I also tested the following configurations:
{
  AT-Utils v1.4.3
  ConfigurableContainers-Core 2.4.0.5
  ModuleManager 2.7.6
} -> no crash

{
  AT-Utils v1.4.3
  ConfigurableContainers-Core 2.4.0.5
  CommunityResourcePack 0.6.6.0
  ModuleManager 2.7.6
} -> no crash

{
  Hangar 3.3.1
  AT-Utils v1.4.2
  ConfigurableContainers-Core 2.4.0.5
  CommunityResourcePack 0.6.6.0
  ModuleManager 2.7.6
} -> no crash

{
  Hangar 3.3.1.1
  AT-Utils v1.4.2
  ConfigurableContainers-Core 2.4.0.5
  CommunityResourcePack 0.6.6.0
  ModuleManager 2.7.6
} -> no crash, but Hangar has no toolbar button, and no Hangar-specific context menu items appear

**Comment by allista** [comment] 2017-06-07 16:18
Oh... How could i have missed that!
Yes, the last versions of the mods are only compatible with KSP-1.3, because KSP API has changed. **But**, that's about the only thing they're different from the previous versions. This was a compatibility release only. So just stick to the last 1.2.2 compatible versions. The next major releases with new functionality will not be ready for a while, in afraid.

**Comment by Yoochem** [comment] 2017-06-08 09:52
Thanks for the feedback, allista and metalwanderer. I'm glad the source of the problem has been found (and thanks for spotting my double MM dll)! I'm also going to stick to 1.2.2 for a while longer, as I prefer mod compatibility over Chinese-speaking kerbals. 

Love Hangar by the way, thanks for making such a cool mod!

**Comment by allista** [comment] 2017-06-08 21:21
Closing the issue then.

**Closed as completed by allista** 2017-06-08 21:21 UTC
Labels: needs testing
